In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Mounting the google colab drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Importing the dataset
dataset = pd.read_csv('/content/drive/MyDrive/DL/Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [ ]:
# Showing the first 5 rows
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
len(dataset)

10000

In [ ]:
len(X_test)

2000

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Classical ML

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)

print(cm)

[[1363  232]
 [ 182  223]]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test,pred)
print(score*100)

79.3


### Accuracy from Decision Tree Classifier: 80%

In [ ]:
## Random Forest

#Classical ML

from sklearn.ensemble import RandomForestClassifier
clf2 = RandomForestClassifier(n_estimators=200)
clf2.fit(X_train, y_train)
pred2 = clf2.predict(X_test)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test, pred2)

print(cm2)

[[1526   69]
 [ 199  206]]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import accuracy_score

score2 = accuracy_score(y_test,pred2)
print(score2*100)

86.6


### Accuracy from Random Forest Classifier: 87%

# ANN - Let's get started!!

In [ ]:
#pip install keras
#pip install tensorflow

In [ ]:
# Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# Initialising the ANN
classifier = Sequential()
#units: It's an art, comes by experience, input+output/2
#initializer: how your weights are updated
#relu activation function
#input_dim: input shape (shape of the data, how many features do we have in the data)
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the third  hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [ ]:
len(X_train)

8000

In [ ]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
y_train[0]
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 50)

Epoch 1/50
800/800 [==============================] - 3s 2ms/step - loss: 0.4885 - accuracy: 0.7960
Epoch 2/50
800/800 [==============================] - 2s 3ms/step - loss: 0.4315 - accuracy: 0.7960
Epoch 3/50
800/800 [==============================] - 2s 3ms/step - loss: 0.4261 - accuracy: 0.8005
Epoch 4/50
800/800 [==============================] - 2s 2ms/step - loss: 0.4222 - accuracy: 0.8217
Epoch 5/50
800/800 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.8264
Epoch 6/50
800/800 [==============================] - 1s 2ms/step - loss: 0.4189 - accuracy: 0.8301
Epoch 7/50
800/800 [==============================] - 1s 2ms/step - loss: 0.4174 - accuracy: 0.8317
Epoch 8/50
800/800 [==============================] - 1s 2ms/step - loss: 0.4158 - accuracy: 0.8311
Epoch 9/50
800/800 [==============================] - 2s 2ms/step - loss: 0.4150 - accuracy: 0.8332
Epoch 10/50
800/800 [==============================] - 1s 2ms/step - loss: 0.4140 - accuracy: 0.8329

In [ ]:
# Part 3 - Making predictions and evaluating the model
# Predicting the Test set results
y_pred_ann = classifier.predict(X_test)
y_pred_ann = (y_pred_ann > 0.5)

cm3 = confusion_matrix(y_test, y_pred_ann)
print(cm3)

63/63 [==============================] - 0s 1ms/step
[[1535   60]
 [ 256  149]]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import accuracy_score

score3 = accuracy_score(y_test,y_pred_ann)
print(score3*100)

84.2


### Accuracy from ANN: 84%

## Conclusion:

So, as we have already seen, by using 2 hidden layered ANN, we aren't able to get beyond 85% accuracy, ofcourse we can get higher accuracy by increasing the epochs & doing some hyperparameter tuning, so on the other hand, the classical models can also be tuned further.

Bottomline, always start with classical machine learning models, and if we aren't able to increase the performance, then move towards Deep Learning techniques :)

# Hyper Parameter Tuning - Run at your own risk 👍👍




In [ ]:
# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""
new_prediction = classifier.predict(sc.transform(np.array([[600, 0, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)
new_prediction
# Making the Confusion Matrix
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)

array([[False]])

In [ ]:
#Importing few libraries for k-folds
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv =10, n_jobs = -1 )
mean1 = accuracies.mean()
variance = accuracies.std()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  from ipykernel import kernelapp as app


In [ ]:
variance

0.009657399309785705

In [ ]:
accuracies

array([0.83749998, 0.83999997, 0.82999998, 0.81875002, 0.85124999,
       0.82875001, 0.83249998, 0.83625001, 0.81875002, 0.84249997])

In [ ]:
mean1

0.8336249947547912

In [ ]:
#Improvising the ANN - Hyper parameter optimization

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense


def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier


classifier = KerasClassifier(build_fn = build_classifier)

parameters = {'batch_size': [10, 20],
              'epochs': [5, 6]}

              # Total combinations: 4

grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', n_jobs = -1, cv = 5)
grid_search = grid_search.fit(X_train, y_train)
grid_search.best_params_
grid_search.best_score_

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.


Epoch 1/6
800/800 [==============================] - 2s 1ms/step - loss: 0.4852 - accuracy: 0.7958
Epoch 2/6
800/800 [==============================] - 1s 2ms/step - loss: 0.4316 - accuracy: 0.7960
Epoch 3/6
800/800 [==============================] - 1s 1ms/step - loss: 0.4254 - accuracy: 0.8104
Epoch 4/6
800/800 [==============================] - 1s 1ms/step - loss: 0.4189 - accuracy: 0.8278
Epoch 5/6
800/800 [==============================] - 1s 1ms/step - loss: 0.4140 - accuracy: 0.8325
Epoch 6/6
800/800 [==============================] - 1s 1ms/step - loss: 0.4106 - accuracy: 0.8331


0.8256249999999999

In [ ]:
grid_search.best_params_

{'batch_size': 10, 'epochs': 6}

In [ ]:
grid_search.best_score_

0.8256249999999999

In [ ]:
#Improvising the ANN - Hyper parameter optimization, adding more hyperparameters
######################################
######################################
######################################
######################################
#TO DO TASK
######################################
######################################
######################################
######################################

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(loss, optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = loss, metrics = ['accuracy'])
    return classifier


classifier = KerasClassifier(build_fn = build_classifier)

parameters = {'batch_size': [10,20, 30, 50],
              'epochs': [10,50,100,200],
              'loss': ['binary_crossentropy', 'categorical_crossentropy'],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', n_jobs = -1, cv = 10)

grid_search = grid_search.fit(X_train, y_train)

In [ ]:
tuple1 = ([2,3,4],6,7)

In [ ]:
tuple1[0][1]=5

In [ ]:
tuple1

([2, 5, 4], 6, 7)

## Improvising the performance of ANN

1. Increasing the number of hidden layers
2. Increasing the number of epochs
3. Fine-tuning the parameters - optimizers, batch_size, epochs
4. Dropout regularization: Dropout(0.25)

Overfitting problem --> training accuracy increases, but test accuracy is low